version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
      - /app/go/pkg
    ports:
      - "8080:8080"
    privileged: true
    environment:
      - GO_ENV=development